name: landingpage_cebmed
description: "Landing page Cebmed"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_text.png
    - assets/images/logo_two.png
    - assets/images/Cebmed_hero.png
    - assets/images/Caregiver_Mode.png
    - assets/images/mockupthree.png
    - assets/images/instagram-logo.png
    - assets/images/logo-Googleplay.png
    - assets/images/logo-Googleplay.png
    - assets/images/logo_AppStore.png
    - assets/images/App_Cebmed.png
    - assets/images/Instagram_Cebmed.png

  fonts:
    - family: Grandstander
      fonts:
        - asset: assets/fonts/Grandstander-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
