name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Build web app
        run: flutter build web

      - name: Trigger Vercel Deployment
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"